package view;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URL;

public class Images {
    public static URL paint0= Images.class.getResource("/Image/图标.jpg");
    public static ImageIcon paint = new ImageIcon(paint0);
    public static URL background0 = Images.class.getResource("/Image/开始背景.jpg");
    public static ImageIcon background = new ImageIcon(background0);
    public static URL two0 = Images.class.getResource("/Image/双人对战.png");
    public static ImageIcon two = new ImageIcon(two0);
    public static URL two1 = Images.class.getResource("/Image/双人对战_副本.png");
    public static ImageIcon two2 = new ImageIcon(two1);
    public static URL exit0 = Images.class.getResource("/Image/退出游戏.png");
    public static ImageIcon exit = new ImageIcon(exit0);
    public static URL exit1 = Images.class.getResource("/Image/退出游戏_副本.png");
    public static ImageIcon exit2 = new ImageIcon(exit1);
    public static URL background2 = Images.class.getResource("/Image/背景3.jpg");
    public static ImageIcon background1 = new ImageIcon(background2);
    public static URL background4 = Images.class.getResource("/Image/背景改变.png");
    public static ImageIcon background3 = new ImageIcon(background4);
    public static URL background6 = Images.class.getResource("/Image/背景三.jpg");
    public static ImageIcon background5 = new ImageIcon(background6);
    public static URL backchess0 = Images.class.getResource("/Image/棋盘1.png");
    public static ImageIcon backchess = new ImageIcon(backchess0);
    public static URL backchess2 = Images.class.getResource("/Image/棋盘设置.png");
    public static ImageIcon backchess1 = new ImageIcon(backchess2);
    public static URL backchess4 = Images.class.getResource("/Image/棋盘3.png");
    public static ImageIcon backchess3 = new ImageIcon(backchess4);
    public static URL set0 = Images.class.getResource("/Image/设置.png");
    public static ImageIcon set = new ImageIcon(set0);
    public static URL set2 = Images.class.getResource("/Image/设置_副本.png");
    public static ImageIcon set1 = new ImageIcon(set2);
    public static URL undo0 = Images.class.getResource("/Image/上一步.png");
    public static ImageIcon undo = new ImageIcon(undo0);
    public static URL undo2 = Images.class.getResource("/Image/上一步_副本.png");
    public static ImageIcon undo1 = new ImageIcon(undo2);
    public static URL loud0 = Images.class.getResource("/Image/下一步.png");
    public static ImageIcon loud = new ImageIcon(loud0);
    public static URL loud2 = Images.class.getResource("/Image/下一步_副本.png");
    public static ImageIcon loud1 = new ImageIcon(loud2);
    public static URL restart0 = Images.class.getResource("/Image/重新开始.png");
    public static ImageIcon restart = new ImageIcon(restart0);
    public static URL restart2 = Images.class.getResource("/Image/重新开始_副本.png");
    public static ImageIcon restart1 = new ImageIcon(restart2);
    public static URL Exit0 = Images.class.getResource("/Image/退出.png");
    public static ImageIcon Exit = new ImageIcon(Exit0);
    public static URL Exit2 = Images.class.getResource("/Image/退出_副本.png");
    public static ImageIcon Exit1 = new ImageIcon(Exit2);
    public static URL sort0 = Images.class.getResource("/Image/排行榜.png");
    public static ImageIcon sort = new ImageIcon(sort0);
    public static URL sort2 = Images.class.getResource("/Image/排行榜_副本.png");
    public static ImageIcon sort1 = new ImageIcon(sort2);
    public static URL white_p1 = Images.class.getResource("/Image/白方兵.png");
    public static ImageIcon white_p = new ImageIcon(white_p1);
    public static URL white_q1 = Images.class.getResource("/Image/白方后.png");
    public static ImageIcon white_q = new ImageIcon(white_q1);
    public static URL white_k1 = Images.class.getResource("/Image/白方王.png");
    public static ImageIcon white_k = new ImageIcon(white_k1);
    public static URL white_b1 = Images.class.getResource("/Image/白方象.png");
    public static ImageIcon white_b = new ImageIcon(white_b1);
    public static URL white_r1 = Images.class.getResource("/Image/白方车.png");
    public static ImageIcon white_r = new ImageIcon(white_r1);
    public static URL white_n1 = Images.class.getResource("/Image/白方马.png");
    public static ImageIcon white_n = new ImageIcon(white_n1);
    public static URL black_p1 = Images.class.getResource("/Image/黑方兵.png");
    public static ImageIcon black_p = new ImageIcon(black_p1);
    public static URL black_q1 = Images.class.getResource("/Image/黑方后.png");
    public static ImageIcon black_q = new ImageIcon(black_q1);
    public static URL black_k1 = Images.class.getResource("/Image/黑方王.png");
    public static ImageIcon black_k = new ImageIcon(black_k1);
    public static URL black_b1 = Images.class.getResource("/Image/黑方象.png");
    public static ImageIcon black_b = new ImageIcon(black_b1);
    public static URL black_r1 = Images.class.getResource("/Image/黑方车.png");
    public static ImageIcon black_r = new ImageIcon(black_r1);
    public static URL black_n1 = Images.class.getResource("/Image/黑方马.png");
    public static ImageIcon black_n = new ImageIcon(black_n1);
    public static URL loudin0 = Images.class.getResource("/Image/人机对战.png");
    public static ImageIcon loudin = new ImageIcon(loudin0);
    public static URL loudin2 = Images.class.getResource("/Image/人机对战_副本.png");
    public static ImageIcon loudin1= new ImageIcon(loudin2);
    public static URL black0 = Images.class.getResource("/Image/黑方头像.png");
    public static ImageIcon black = new ImageIcon(black0);
    public static URL white0 = Images.class.getResource("/Image/白方头像.png");
    public static ImageIcon white = new ImageIcon(white0);


}